sonar.projectKey=kripashetty_weave-api
sonar.organization=kripashetty
sonar.projectName=weave-api
sonar.projectVersion=0.1.0

# Source
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/alembic/**,**/__pycache__/**,**/node_modules/**
sonar.test.exclusions=tests/**
